FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /app

# Copiar o projecto completo para o directorio app
COPY . /app/

# Restaurar as camadas distintas
RUN dotnet restore

#Build and Publish a release
RUN dotnet publish -c Release -o out

#Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
LABEL author="MAS INOVACOES,LDA"
ENV ASPNETCORE_ENVIRONMENT=Production
WORKDIR /app/mas.ao/ibge
EXPOSE 80
EXPOSE 443

RUN mkdir /app/mas.ao/ibge/Logs
COPY --from=build-env /app/out ./
ENTRYPOINT ["dotnet", "IBGE.Apis.dll"]